Update stepper design
kiwicom/orbit-compose pull request #135
Opened 2022-04-13 07:15 UTC by zurdus

2022-04-13 07:45 UTC, hrach requested changes

2022-04-13 07:45 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +public fun StepperInteractive(
Please, make this `active: Boolean` as was defined this in the ticket. This gonna be rather dynamic property, I expect that it will be usually something like `active = value > 0`.

2022-04-13 07:45 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +        onValueChange = onValueChange,
Please, move all Modifier to proper place -> the first optional parameter.

2022-04-13 07:45 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +                modifier = Modifier.defaultMinSize(44.dp)
shouldn't be this rather minWidth?

2022-04-13 07:45 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +        contentColor = contentColor,
There is missing background color change in disabled state as defined in Figma.
I'd recommend something like

```kotlin
color = if (enabled) backgroundColor else backgroundColor.copy(alpha = 0.7),
contentColor = contentColorFor(backgroundColor),
```

(e.g. also dropping the contentColor parameter)

2022-04-13 07:45 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +    addContentDescription: String = stringResource(id = R.string.orbit_cd_stepper_add),
No need for defaults here.

2022-04-13 07:57 UTC, gerak-cz reviewed
Looks good 👍

2022-05-20 15:04 UTC, hrach commented
Hi @zurdus. I have fixed/modified few things and squashed them here: https://github.com/kiwicom/orbit-compose/compare/stepper-update?expand=1 Please open the pull request to be its author.

Anyway, those changes mainly are:
- indication feedback outside the button (44dp diameter)
- smaller animation (height / 2)

2022-05-26 08:00 UTC, closed without merging