Created BadgePrimitive and added bundle gradient badges
kiwicom/orbit-compose pull request #185
Opened 2022-07-12 12:28 UTC by zurdus

2022-07-12 12:28 UTC, zurdus commented on catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeScreen.kt
> -            BadgeCircleNeutral(value = 1)
I deleted all these because they're already showcased in their own category below.

2022-07-12 18:37 UTC, hrach requested changes

2022-07-12 18:37 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +    shape: Shape = RoundedCornerShape(50),
Please don't expose those properties + textStyle.

2022-07-12 18:37 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +    icon: (@Composable () -> Unit)? = null,
Make icon non nullable, default just `{}`

2022-07-12 18:37 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +        ) {
Please reset ContentEmphasis to Normal

2022-07-12 18:37 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +public object BadgeDefaults {
Since it won't be public in the end, use just simply top-level constants.

2022-07-12 18:37 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +    contentColor: Color? = null,
Make it non nullable and use `contentColorFor(backgroundColor)` as it is default value in ButtonPrimitive. Those using brush will have to pass the value manually (that's quite ok)

2022-07-12 18:37 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Badge.kt
> +        BadgeBundleBasic(
New screenshot has to be rendered and committed. See https://github.com/kiwicom/orbit-compose/blob/main/contributing.md#screenshot-testing

2022-07-12 18:39 UTC, hrach requested changes
Also, please add Circle variants.

2022-07-18 08:22 UTC, zurdus commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +    shape: Shape = RoundedCornerShape(50),
None of these? Apart from `borderWidth `and `arrangement`, the other ones, and also `textStyle`, are available for `PrimitiveButton`

2022-07-18 08:38 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/BadgePrimitive.kt
> +    shape: Shape = RoundedCornerShape(50),
Yeah, because content padding is dynamic in Orbit. Background brush is ok.

2022-07-18 17:31 UTC, merged