custom lint for composables
kiwicom/orbit-compose pull request #191
Opened 2022-07-16 20:01 UTC by shalva97

A while back I suffered by mistakenly used the wrong composable, again... few days later found a custom lint on[ this project](https://github.com/android/nowinandroid) so maybe we can also have it here for Kiwi, so people will know about the wrong components they will use.

It took me few hours but got it sort of working with example checks. Most likely it will take a lot more hours... So will open this, maybe you dont need this functionality.

Here are some problems to fix:

- I imagine, that when one adds dependency to `implementation "kiwi.orbit.compose:ui:<version>"` they will also get few lint rules, but if they add icons or illustrations they wont get any. 
- At least one module should call `lintPublish(project(":lint"))` so the lint rules will be picked up by lint, currently I have added it to `ui` module, which is also complaining about code inside there. maybe it will somehow work if I add another module, but I dont know how it will work...
- add actual data for the lint rules for checking Kiwi composables

So what do you think? is this a good idea to add?

2022-07-18 06:43 UTC, hrach requested changes
Thank you for this great contribution. We were planning this! So great to have it earlier. Please let's finish it a bit. Drop the copy right headers as those files will be quite different and please clean it upa bit. 

We don't have to have full list, let's start with some small linting :)

2022-07-18 06:43 UTC, hrach commented on lint/src/main/java/kiwi/orbit/compose/KiwiIssueRegistry.kt
> +class KiwiIssueRegistry : IssueRegistry() {
Let's use OrbitCompose name here

2022-07-18 06:43 UTC, hrach commented on lint/src/main/java/kiwi/orbit/compose/detectors/KiwiDesignSystemDetector.kt
> +            briefDescription = "Kiwi Design system",
id = OrbitComposeDesignSystem
briefDescription = "Usage of Material UI instead of Orbit Compose UI"

2022-07-23 23:30 UTC, hrach commented
Thank you for the great work. I've finished the naming and testing and the result is in #198. Closing here.

2022-07-23 23:30 UTC, closed without merging

2022-07-24 14:26 UTC, shalva97 commented
hey, why not warn about this? what if I had some unfinished work commited locally?

2022-07-24 18:28 UTC, hrach commented
@shalva97 I'm sorry, I will be more cautious next time. I somehow expected that the PR is "done" though not fully merge-able and therefore I finished it. I guess marking the PR as a [draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) would make it more clear for me. The commit properly attributes you as co-author.