Expanded readme file
kiwicom/orbit-compose pull request #194
Opened 2022-07-18 07:57 UTC by zurdus

2022-07-18 09:10 UTC, hrach requested changes

2022-07-18 09:10 UTC, hrach commented on readme.md
> +    }
I'd show only Orbit Components. Lets add something else, I'd use Alert, it looks nice and is simple.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +![Result of the code above](https://user-images.githubusercontent.com/6010616/179000669-65bb57cb-d2e4-42d6-a35b-3aa9867e3705.png)
I'd recommend adding the screenshot to the repo and normally commit it and reference it.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +You can take a look at our component catalog by downloading and installing our [showcase application](https://play.google.com/store/apps/details?id=kiwi.orbit.compose.catalog) on Google Play.
Let's use a capital C to for the name. Also, we dont install it on Google Play, but rather from, right?

2022-07-18 09:10 UTC, hrach commented on readme.md
> +## Samples and documentation
I'd use just "Documentation" - samples are kind of documentation.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +The documentation for this project can be found [here](https://kiwicom.github.io/orbit-compose/).
The "API documentation". Also, here is is common [linking mistake](https://heyoka.medium.com/dont-use-click-here-f32f445d1021).

```
The [API documentation](https://kiwicom.github.io/orbit-compose/) lists 
all possible types and composables in Orbit Compose library.
```

or ~ similar?

2022-07-18 09:10 UTC, hrach commented on readme.md
> +You can help us make this library better by reporting any issues you find using the [Issues tab](https://github.com/kiwicom/orbit-compose/issues).
This should rather link contributing.md and add content there.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +- Compliance with our API requirements.
Not much value in it, though contributing.md could bear it.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +Any feedback you have for us is appreciated. If you have any suggestions about what we can do, do not hesitate to [report the issue](https://github.com/kiwicom/orbit-compose/issues), or contact us at
I don't know about this Slack channel; it is needed to say which workspace we're talking about and how to get there/sign up. But since we don't have it, I think we should remove it here.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +We publish our releases in [Maven Central](https://search.maven.org/search?q=g:kiwi.orbit.compose). To use this library, you can add the following dependencies to your **gradle file**:
capital G.

2022-07-18 09:10 UTC, hrach commented on readme.md
> +## Download
"Setup" and I'd merged it somehow with Hot to use.

2022-07-18 09:27 UTC, zurdus commented on readme.md
> +    }
I'll add the alert. For this screenshot, I added the normal button because I wanted to show the minimal difference between a Material composable and an Orbit one. I found that valuable for the readme. Wdyt?

2022-07-18 12:22 UTC, zurdus commented on readme.md
> +## Download
Now that the **How to Use** section is bigger, I think it makes sense to keep it separated.

2022-07-19 08:27 UTC, hrach requested changes
Great! Almost there :)

2022-07-19 08:27 UTC, hrach commented on readme.md
> +![Result of the code above](./readme_img/orbit_styled_text.png)
Those screenshots are too big (bit overhelming), let's remove the "Foundation elements" heading and put both screenshots here next to each other (this will decrease their width), cca like this:

```kotlin
<table>
<tr><td>

![Orbit Button and Alert component](./readme_img/orbit_styled_text.png)

<td>

![Orbit typography and colors](...)

</table>
```

2022-07-19 08:27 UTC, hrach commented on readme.md
> +![Result of the code above](./readme_img/button_and_alert.png)
Please move those images into `docs/readme/_.png` path as we will introduce more docs later in that dir.

2022-07-19 09:49 UTC, zurdus commented on readme.md
> +![Result of the code above](./readme_img/orbit_styled_text.png)
I don't love the borders in the table, but apparently there's nothing we can do, as Github removes styling in HTML

2022-07-19 10:47 UTC, hrach approved these changes

2022-07-19 10:47 UTC, hrach commented on readme.md
>  ```
One small thing, put `kotlin` here (and there) after the tripple backtip to get highlighting.

2022-07-19 11:00 UTC, merged