Implement `Dialog()` component
kiwicom/orbit-compose pull request #233
Opened 2022-08-29 14:53 UTC by Drekorian

![ezgif com-gif-maker](https://user-images.githubusercontent.com/125338/187228411-f3388aae-bd2a-4c8a-a5d8-399041651de4.gif)

Implements Orbit `Dialog()` component. Property naming has been taken out out Material's `AlertDialog()` component. Screenshots for Paparazzi are taken from `DialogContent()` since there's a built-in animation for Compose `Dialog()` and Paparazzi cannot capture it properly at the moment.

2022-08-29 15:05 UTC, hrach requested changes

2022-08-29 15:05 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +    title: @Composable () -> Unit = {},
Let's not make it optional and put it over text to better shape the API ordering.

2022-08-29 15:05 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +public fun Dialog(
Maybe some KDOC? Mentioning which buttons to use and so?

2022-08-29 15:05 UTC, hrach commented on ui/src/test/kotlin/ScreenshotTest.kt
> +    fun dialogMultipleActions() {
I guess one screenshot type is quite ok, but let's add an icon or some placeholder to the illustration slot.

2022-08-30 07:15 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +    text: @Composable () -> Unit,
On the Personal details screen we want to present user with options when he clicks on the avatar.

Dialog should be used and in this case and no texts are actually needed, the text on the buttons is enough.

I am not sure if this component is appropriate in this case but if so, these texts should be optional and the dialog should be optimized for such case.

2022-08-30 07:31 UTC, Drekorian commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +    text: @Composable () -> Unit,
Something like this? 🤔

![weird-dialog](https://user-images.githubusercontent.com/125338/187376804-c15f1daf-5cc1-4cc9-acf0-908fc47635e7.png)

2022-08-30 07:40 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +    text: @Composable () -> Unit,
Yeah, it will fail because the top doubled 16.dp. But I guess this is expected, a question should be presented, at least something like "Choose how to pick a photo:"

2022-08-30 07:41 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +                    top = 24.dp,
I'm a bit worried about this one. It seems this is compensation for wrong illustration proportions and when the dialog is used without an illustration, it creates inappropriate padding on the top. I'll ping Orbit about this.

2022-08-30 07:48 UTC, Drekorian commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +    text: @Composable () -> Unit,
I think a modal without any instructions whatsoever is a bit strange.

2022-08-30 08:07 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +    text: @Composable () -> Unit,
Alright

2022-09-01 10:04 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +                    top = 24.dp,
Official response: it will be decreased to 16.dp and dialogs without illustration are an official thing. @Drekorian 🙏

2022-09-01 21:32 UTC, Drekorian commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Dialog.kt
> +                    top = 24.dp,
Done! I hope these are satisfactory.

![dialog-with-illustration](https://user-images.githubusercontent.com/125338/188016811-0b8786cf-5ea2-49f5-b380-7e741046d7d4.png)

![dialog-without-illustration](https://user-images.githubusercontent.com/125338/188016836-ba7df4df-219e-437d-b08b-ebdccfa5d66d.png)

2022-09-01 21:33 UTC, hrach approved these changes

2022-09-01 21:48 UTC, merged