Implement BadgeList component (#289)
kiwicom/orbit-compose pull request #290
Opened 2022-11-30 14:49 UTC by rusnacok

2022-11-30 15:56 UTC, hrach requested changes
LGTM! Two little things to fix.

2022-11-30 15:56 UTC, hrach commented on catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
> +        MenuItem("BadgeList", Icons.AirplaneReturn) { Destinations.BadgeList },
Please use Icons.List

2022-11-30 15:56 UTC, hrach commented on catalog/src/main/java/kiwi/orbit/compose/catalog/screens/BadgeListScreen.kt
> +        BadgeListSmall(contentEmphasis = ContentEmphasis.Minor) {
BadgeList only

2022-12-01 08:20 UTC, rusnacok commented on catalog/src/main/java/kiwi/orbit/compose/catalog/screens/MainScreen.kt
> +        MenuItem("BadgeList", Icons.AirplaneReturn) { Destinations.BadgeList },
OK

2022-12-01 09:11 UTC, hrach approved these changes

2022-12-01 09:12 UTC, merged

2022-12-01 09:12 UTC, hrach commented
👍