Add Stepper Semantics
kiwicom/orbit-compose pull request #293
Opened 2022-12-06 14:05 UTC by DavidGrygar

2022-12-06 14:13 UTC, hrach requested changes

2022-12-06 14:13 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +}
We want to expose those data other way. Please expose it via standard/custom semantic properties on the whole stepper -> value on it, action callbacks on it, etc.

2022-12-06 14:39 UTC, DavidGrygar commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +}
I don't understand how I can add semantic property for whole stepper if enabled information is inside `StepperButton`.

2022-12-06 17:27 UTC, DavidGrygar commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Stepper.kt
> +}
Without testTags I can close this MR, because if I get buttons with `.onChildAt(0)` or `.onChildAt(2)` I am able to call `.assertIsEnabled()` or `.assertIsNotEnabled()` on them.

2023-01-17 08:43 UTC, hrach commented
Closing as we will have to rework this differently.

2023-01-17 08:43 UTC, closed without merging