Tile component
kiwicom/orbit-compose pull request #319
Opened 2023-01-18 13:01 UTC by gerak-cz

2023-01-19 12:19 UTC, hrach requested changes
Few things to fix, please add also Tile unit test.

2023-01-19 12:19 UTC, hrach commented on .idea/codeStyles/Project.xml
> -      <option name="LINE_BREAK_AFTER_MULTILINE_WHEN_ENTRY" value="false" />
Please drop this from PR, as it is needed in newer AS/IntelliJ platforms.

2023-01-19 12:19 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
> +                ProvideMergedTextStyle(OrbitTheme.typography.title4) {
I'd use bodyNormal here as no title is expected.

2023-01-19 12:19 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
> +        modifier = modifier.height(IntrinsicSize.Max),
This is not needed, isn't it?

2023-01-19 12:19 UTC, hrach commented on docs/03-components/02-structure/tile.mdx
> +`Tile` component is elevated clickable item with trailing indication of further action.
Please update the overview similarly to other chapters - i.e. put a list of composables with links to API docs.

2023-01-19 12:19 UTC, hrach commented on docs/03-components/02-structure/tile.mdx
> +By default the `trailingContent` displays forward chevron icon.
RowScope or RowScope.align should use ` wrapping.

2023-01-19 12:19 UTC, hrach commented on docs/03-components/02-structure/tile.mdx
> +composeTestRule.onNodeWithTag("description").assertTextEquals("Description")
Please put a showcase of click here. See button.

2023-01-19 12:42 UTC, gerak-cz commented on .idea/codeStyles/Project.xml
> -      <option name="LINE_BREAK_AFTER_MULTILINE_WHEN_ENTRY" value="false" />
Ok, this is annoying change that is generated automatically by AS.

2023-01-19 13:02 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
> +                ProvideMergedTextStyle(OrbitTheme.typography.title4) {
It is true that the trailing content style is not connected to the title style as icon style is. It is more of a coincidence that the default trailing icon has the same size.

2023-01-19 13:07 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
> +                ProvideMergedTextStyle(OrbitTheme.typography.title4) {
Yeah, and since bodyNormal has the same as well, it seems a better option to go with he more common/default typography style.

2023-01-20 11:27 UTC, gerak-cz commented on docs/03-components/02-structure/tile.mdx
> +`Tile` component is elevated clickable item with trailing indication of further action.
Added link to the generated documentation.

2023-01-20 11:42 UTC, hrach approved these changes
LGTM, please last bits.

2023-01-20 11:42 UTC, hrach commented on docs/03-components/02-structure/tile.mdx
> +            )
Please use existing CustomPlaceholder()

2023-01-20 11:42 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
> +            )
dto

2023-01-20 11:43 UTC, hrach commented on catalog/src/main/java/kiwi/orbit/compose/catalog/screens/TileScreen.kt
> +            )
Here, not in doc.

2023-01-20 11:43 UTC, hrach commented on docs/03-components/02-structure/tile.mdx
> +            )
Oh, here in doc - maybe make it more simple, CustomPlaceholder is not good option here.

2023-01-20 12:11 UTC, hrach approved these changes

2023-01-20 12:17 UTC, merged