add Collapse Component
kiwicom/orbit-compose pull request #381
Opened 2023-03-22 09:42 UTC by yveskalume

closes #348

2023-03-22 19:31 UTC, hrach requested changes
Thank you for this contribution. Good job 👍 Just a few naming things and the semantics custom action to fix.

Maybe you could use our CustomPlaceholder() helper to visualize it with the green box in the preview/screenshot.

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +    showSeparator: Boolean = true,
We already have this arg in ListChoice and we call it `withSeparator`, so I'd name it here the smae.

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +    body: @Composable () -> Unit,
Please name it content and make it the last argument.

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +    header: @Composable () -> Unit,
Please name it title.

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +    isExpended: Boolean,
Just expanded

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +    onExpandChange: (Boolean) -> Unit,
onExpandClick, or onExpandToggle? What do you think?

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +            CollapseArrow(isExpended = isExpended, onClick = { onExpandChange(!isExpended) })
Please take a look here https://www.figma.com/community/file/832545093919910941/%5BOrbit-Design-System%5D-Native-App-Components (switch the page in preview to collapsible) We would need to update it a bit:

The collapsing icon should be on the right without the padding from end, maybe we can use something like offset?

2023-03-22 19:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +            .testTag("collapse_arrow"),
This is a bit problematic - we don't use this pattern in the library. I.e. it would be great to expose the click here as a custom action through semantics.

2023-03-23 06:29 UTC, Drekorian requested changes

2023-03-23 06:29 UTC, Drekorian commented on docs/03-components/07-interaction/collapse.mdx
> +    var isExpended by remember { mutableStateOf(false) }
Typo: `isExpanded`.

2023-03-23 06:29 UTC, Drekorian commented on docs/03-components/07-interaction/collapse.mdx
> +Use `Collapse` composable and define a boolean state passe it to `isExpended`. Process the value in `onExpandChange` callback.
Typo `isExpanded`. Not sure what do you mean by `passe`.

2023-03-23 06:29 UTC, Drekorian commented on docs/03-components/07-interaction/collapse.mdx
> +    var isExpended by remember { mutableStateOf(false) }
Typo `isExpanded`.

2023-03-23 06:29 UTC, Drekorian commented on docs/03-components/07-interaction/collapse.mdx
> +    var isExpended by remember { mutableStateOf(false) }
Typo: `isExpanded`.

2023-03-23 06:29 UTC, Drekorian commented on ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/CollapseTest.kt
> +            var isExpended by remember { mutableStateOf(false) }
Typo: `isExpanded`.

2023-03-24 09:07 UTC, yveskalume commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +    onExpandChange: (Boolean) -> Unit,
IMO we can use `onExpandClick`

2023-03-24 09:13 UTC, yveskalume commented on docs/03-components/07-interaction/collapse.mdx
> +Use `Collapse` composable and define a boolean state passe it to `isExpended`. Process the value in `onExpandChange` callback.
Sorry i'm not a native English speaker, I correct it !

2023-03-24 18:56 UTC, Drekorian commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Collapse.kt
> +            .testTag("collapse_arrow"),
`Collapse.kt`

```kotlin
@Composable
public fun Collapse(
    isExpended: Boolean,
    onExpandChange: (Boolean) -> Unit,
    header: @Composable () -> Unit,
    body: @Composable () -> Unit,
    modifier: Modifier = Modifier,
    showSeparator: Boolean = true,
) {
    Column(
        modifier = modifier.semantics {
            this[SemanticsActions.Expand] = AccessibilityAction(SemanticsActions.Expand.name) {
                if (!isExpended) {
                    onExpandChange(true)
                    true
                } else {
                    false
                }
            }
            this[SemanticsActions.Collapse] = AccessibilityAction(SemanticsActions.Collapse.name) {
                if (isExpended) {
                    onExpandChange(false)
                    true
                } else {
                    false
                }
            }
        },
```

`CollapseTest.kt`

```kotlin
composeTestRule.setContent {
            var isExpended by remember { mutableStateOf(false) }
            Collapse(
                isExpended = isExpended,
                onExpandChange = { isExpended = it },
                header = {
                    Text(text = "This the header", modifier = Modifier.testTag("header"))
                },
                body = {
                    Text(text = "This is the collapsible body", modifier = Modifier.testTag("body"))
                },
                modifier = Modifier.testTag("collapse"),
            )
        }

        composeTestRule.onNodeWithTag("header").assertIsDisplayed()
        composeTestRule.onNodeWithTag("body").assertDoesNotExist()

        composeTestRule.onNodeWithTag("collapse").performSemanticsAction(SemanticsActions.Expand)
        composeTestRule.onNodeWithTag("body").assertIsDisplayed()

        composeTestRule.onNodeWithTag("collapse").performSemanticsAction(SemanticsActions.Collapse)
        composeTestRule.onNodeWithTag("body").assertDoesNotExist()
```

2023-03-25 11:56 UTC, Drekorian approved these changes

2023-03-25 11:56 UTC, Drekorian commented on catalog/src/main/java/kiwi/orbit/compose/catalog/screens/CollapseScreen.kt
> +    var isFirstCollapseExtended by remember { mutableStateOf(true) }
**Nitpick:** I would stick to the terms _Expand_, _Expanded_, _Collapse_ and _Collapsed_ since it correlates to the `SemanticsAction` you're using.

2023-03-25 11:56 UTC, Drekorian commented on docs/03-components/07-interaction/collapse.mdx
> +composeTestRule.onNodeWithTag("body").assertDoesNotExist()
The testing documentation should be updated based on your solution in `CollapseTest.kt`.

2023-03-25 11:56 UTC, Drekorian commented on ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/CollapseTest.kt
> +                Modifier.testTag("collapse"),
**Nitpick:** since you're naming the other arguments, I would name the `modifier` as well.

2023-03-27 14:42 UTC, merged