Add tilegroup implementation
kiwicom/orbit-compose pull request #448
Opened 2023-06-07 12:34 UTC by shanio

2023-06-07 14:22 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Tile.kt
> +            onClick,
nit: All other arguments are named.

2023-06-07 14:22 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
> +        val columnHeight = placeables.sumOf { it.height }
Shouldn't this be subjected to the constraints?

2023-06-08 07:31 UTC, hrach requested changes
Very nice. Few things to fix.

2023-06-08 07:31 UTC, hrach commented on ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/TileGroupTest.kt
> +        composeTestRule.onNodeWithTag("tileGroup").onChild().assertTextContains("Title")
Ideally, add a test tag and access the Tile directly - this will check/showcase that the TileGroup doesn't merge trees and make the slots accessible the standard way.

2023-06-08 07:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
> +        // drop the last measurable, typically the last separator added by [TileGroupScope.Tile].
Maybe we could check (`check() {}`) that the number of measurables is even. Just to be sure it is not used in the wrong way. It won't cover every bad usage, but it may help in some cases.

2023-06-08 07:31 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
> +            TileGroupScopeInstance(separatorStartIndent).content()
TileGroupScopeInstance should be remembered.

2023-06-08 07:31 UTC, hrach commented on ui/src/test/kotlin/kiwi/orbit/compose/ui/controls/TileGroupTest.kt
> +        composeTestRule.onNodeWithTag("tileGroup").onChild().assertTextContains("Title")
In other words, you can be sure then that the documented example is correct :)

2023-06-08 09:09 UTC, shanio commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
> +        val columnHeight = placeables.sumOf { it.height }
I tested it in sample application (within Scaffold) where it does not do any difference. In preview howver the difference can be seen, as it will try to "center" the view in it, cutting the top most and bottom most part.
What is the result then?

2023-06-08 09:28 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
> +        val columnHeight = placeables.sumOf { it.height }
oks from my side.

2023-06-08 09:28 UTC, hrach approved these changes

2023-06-08 10:13 UTC, Drekorian approved these changes

2023-06-08 13:09 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TileGroup.kt
> +        val columnHeight = placeables.sumOf { it.height }
Probably don't have a strong opinion on this. Just though it might be the correct approach to apply the constraints.

2023-06-08 13:35 UTC, merged