Refactor TopAppbar and fix RTL back arrow icon.
kiwicom/orbit-compose pull request #45
Opened 2021-11-01 11:46 UTC by zurdus

2021-11-01 13:40 UTC, hrach requested changes

2021-11-01 13:40 UTC, hrach commented on icons/src/main/java/kiwi/orbit/compose/icons/Icons.kt
> +    public val ArrowBack: Painter
This class is auto-generated, please use the new drawables directly with painterResource. 
I'd suggest also moving the resources to UI packages as we will avoid regenerating issues here.

2021-11-01 13:40 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
> +public fun TopAppBar(
We use other code style here - the official. It should work out of the box in IDE, doesn't it?

2021-11-01 13:40 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
> +    val isRtl = LocalContext.current.resources.configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL
Use LocalLayoutDirection.current

2021-11-01 13:40 UTC, hrach commented on icons/src/main/res/drawable/ic_orbit_arrow_back.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Please name these with left and right name -> the word "forward" (or backward") is RTL|LTR actually is dependent.

2021-11-01 13:40 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
> +      insets = LocalWindowInsets.current.statusBars,
Please use systemBars to apply also padding for navigation bar.

2021-11-01 13:40 UTC, hrach commented on ui/src/main/res/values/strings.xml
> +    <string name="orbit_cd_back_button">Navigate up</string>
this is Up, not back action, so the key should be named rather differently - `orbit_cd_navigate_up` ?

2021-11-01 13:40 UTC, hrach commented on icons/src/main/res/drawable/ic_orbit_arrow_forward.xml
> +        android:scaleX="-1">
Nice trick!

2021-11-02 08:17 UTC, zurdus commented on icons/src/main/res/drawable/ic_orbit_arrow_forward.xml
> +        android:scaleX="-1">
😁 pretty handy, right?

2021-11-02 09:12 UTC, zurdus commented on icons/src/main/java/kiwi/orbit/compose/icons/Icons.kt
> +    public val ArrowBack: Painter
Done.

2021-11-02 09:13 UTC, zurdus commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
> +public fun TopAppBar(
Done.

2021-11-02 09:14 UTC, zurdus commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
> +    val isRtl = LocalContext.current.resources.configuration.layoutDirection == View.LAYOUT_DIRECTION_RTL
I didn't know this one existed, thanks.

2021-11-02 09:14 UTC, zurdus commented on icons/src/main/res/drawable/ic_orbit_arrow_back.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Done.

2021-11-02 09:15 UTC, zurdus commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/TopAppBar.kt
> +      insets = LocalWindowInsets.current.statusBars,
Done.

2021-11-02 09:15 UTC, zurdus commented on ui/src/main/res/values/strings.xml
> +    <string name="orbit_cd_back_button">Navigate up</string>
Done.

2021-11-02 13:19 UTC, hrach approved these changes

2021-11-02 13:31 UTC, merged