Properly handle action's height being larger than available content height
kiwicom/orbit-compose pull request #505
Opened 2023-08-16 10:31 UTC by shanio

#504

2023-08-16 20:20 UTC, Drekorian approved these changes

2023-08-19 13:48 UTC, hrach requested changes
There are some visual glitches as can be seen here:
![obrazek](https://github.com/kiwicom/orbit-compose/assets/284263/66cb0a0b-22a6-4ae7-aacf-b65c3f897474)


Also, practically, the action slot should be probably limited to something like 50% of the available space to keep the content practically accessible. Covering the "content" by another "content" should be done differently  - instead of misusing the action slot.

I'll double-check the actual changes on Monday.

2023-08-21 13:26 UTC, shanio commented
@hrach The changes applied are only fixing the underlying issues in height calculation when the action is too big. The space given to the content is deliberately not capped at the moment (similar to the original state), however the nature of the action slot is that it leaves 8.dp for content in form of gradient.

"The glitches" are actually parts of content, that is being shrunk to 8.dp, which is imo a little bit unexpected (tha action appears to the user as if it is above the content, not sharing/ taking away space from it. )

A fix size/ratio/weight could be applied as suggested, however it might not be so obvious, what would be a good value there. Also the problem will not be fixed by this completely. We will need to either disallow placing custom content into action slot or make sure that scrolling is applied in usage sites.

TL;DR: Making the action slot smaller needs to be coupled with fixes on the usage sites to ensure they fits, while this fix alone preserves the status quo of the component, it just does not allow to crash in those situations.

2023-08-22 08:05 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt
> +        val occupiedBottomSize = if (actionHeight > 0) {
Please keep the naming - e.g. `contentBottom` here. This way it is inconsistent - size is actually height, and occupied is put here but not to other vars. Similarly, keep the contentTop please instead of topBarHeight.

2023-08-22 08:11 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt
> +                .copy(maxHeight = (constraints.maxHeight - padding - top).coerceAtLeast(0)),
using offset(vertical) is probably better as it accounts for max sizes and do the coercing for you:
```kotlin
                .offset(
                    horizontal = padding * -2,
                    vertical = -padding - top,
                ),
```

2023-08-22 09:27 UTC, shanio commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/Scaffold.kt
> +        val occupiedBottomSize = if (actionHeight > 0) {
Changed and renamed/preserved based on our discussion.

2023-08-22 09:49 UTC, hrach approved these changes
LGTM, screenshots have to be updated

2023-08-23 06:26 UTC, merged