Textfield focus glow
kiwicom/orbit-compose pull request #566
Opened 2023-10-26 12:54 UTC by gerak-cz

closes #538

2023-10-27 06:41 UTC, Drekorian approved these changes

2023-10-27 09:12 UTC, hrach requested changes

2023-10-27 09:12 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +            InputState.Focused, InputState.FocusedError -> OrbitTheme.colors.info.normal
FocusedError should stay red with red glow.

2023-10-27 09:12 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +    glowColor: Color = borderColor.copy(alpha = borderColor.alpha * 0.1f),
Those args that animates should be passed as providers/lambdas, to avoid recomposition.

2023-10-27 09:12 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +}
Screenshot to the math - imo outer radius is not big enough.
![obrazek](https://github.com/kiwicom/orbit-compose/assets/284263/e8aa4f4b-a27d-4c0c-8b94-f66ce2c85e59)

2023-10-27 09:12 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/foundation/Shapes.kt
> +internal fun CornerBasedShape.cornerSize(): Dp {
Why do you convert the corner radius to DP, when you - in the end, convert it back to the px? I'd skip that.

2023-10-27 09:12 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +    val glowCornerRadius = CornerRadius((cornerSize + (borderWidth + glowWidth) / 2f).toPx())
I think the math should be `CornerRadius(cornerSizePx + glowWidthPx)`.

2023-10-27 11:20 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +            InputState.Focused, InputState.FocusedError -> OrbitTheme.colors.info.normal
I did not change this. FocusedError was blue.

2023-10-27 11:23 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +}
I used the math you recommended.

I think it might be an optical illusion because the border blue is visually much stronger.

2023-10-27 11:24 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/foundation/Shapes.kt
> +internal fun CornerBasedShape.cornerSize(): Dp {
Yes, but the Dp is generally much more usable, and in all the methods I use sizes in Dp. It would be odd to have one in Px.

2023-10-27 11:25 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +    val glowCornerRadius = CornerRadius((cornerSize + (borderWidth + glowWidth) / 2f).toPx())
No, the lines are drawn around the vectors. So you have half of the border width and half of the glow width.

2023-10-27 12:42 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +    glowColor: Color = borderColor.copy(alpha = borderColor.alpha * 0.1f),
done

2023-10-30 07:41 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +            InputState.Focused, InputState.FocusedError -> OrbitTheme.colors.info.normal
done

2023-10-30 07:42 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +        transitionSpec = { spring(Spring.DampingRatioHighBouncy) },
I thought it looked cool, but okay, let's be boring.

2023-10-30 08:43 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/foundation/Shapes.kt
> +internal fun CornerBasedShape.cornerSize(): Dp {
Ok, hardcoded.

I was thinking about exposing the constants of the corner sizes used to construct the shapes. One downside is that if the LocalShapes would change, the corner size constants would remain the same. So I scraped this option and wanted to produce the corner size from the shapes alone. But as you can see it is pretty difficult.

2023-10-30 09:29 UTC, gerak-cz commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +    val glowCornerRadius = CornerRadius((cornerSize + (borderWidth + glowWidth) / 2f).toPx())
Hmm .. didn't know Figma rendered it that way. Changed.

2023-10-30 15:27 UTC, hrach approved these changes
Last comment, otherwise LGTM.

2023-10-30 15:27 UTC, hrach commented on ui/src/androidMain/kotlin/kiwi/orbit/compose/ui/controls/TextField.kt
> +    val cornerSize = provideCornerSize()
Please, let's not overengineer it. if something is static, use the constant directly without passing the constant as arguments (and also through its own factory).

2023-10-31 08:00 UTC, merged