#1: Implement Orbit Seat
kiwicom/orbit-compose pull request #61
Opened 2021-12-13 16:06 UTC by Drekorian

2021-12-14 07:58 UTC, gerak-cz reviewed
Looks good

2021-12-14 09:50 UTC, hrach requested changes

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +                contentDescription = null,
I'd say we may want to provide content description here.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +    SeatOffsetContainer(
I do not see any value in extracting 3 modifiers to custom Container wrapper.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +import kiwi.orbit.compose.ui.controls.SeatConstants.width
Those imports make it extremely difficult understand what kind of value it is. Please keep the style making it PascalCased constant without any object wrapping.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +        SeatContainer {
The same applies here. For the sake of readability, I'd put here the culumn directly and rather extract the body, as commented bellow.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +            }
Extract to Seat() composable.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +            }
Extract to SeatPrice() composable.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +    Seat(
I'd rather rename this to SeatContainer() and name "Seat" the particular parts -> actual Seat.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +                    isExtraLegroom -> Color(0xFFB4DBF8)
Well, since it is not in orbit colors, let's use the tokens at least -> `ColorTokens.BlueLightActive`

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +                    else -> Color(0xFFC0E8E4)
`ColorTokens.ProductLightActive`

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +                    !enabled -> OrbitTheme.colors.surface.strong
Shouldn't be this `ColorTokens.CloudLightHover` (`#F5F7F9`) instaed of `ColorTokens.CloudDark` (`#E8EDF1`)

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +                                    color = OrbitTheme.colors.primary.onMain,
This is not correct color for selected interactive, you should use `interactive.onMain` for that case.

2021-12-14 09:50 UTC, hrach commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/Seat.kt
> +                                    color = ColorTokens.ProductDarker.copy(alpha = 0.5f),
I know this is in design, though not in Orbit designs. I'd recommend using the Dark variant (optionally apply 0.4f alpha for both here).

It is also a question if Orbit component should support the alpha here. /shrug.

Also I would extract the content color resolution before modifying the style here.

2021-12-15 21:22 UTC, hrach approved these changes

2021-12-15 21:22 UTC, merged