Add the `SeatLegend()` component
kiwicom/orbit-compose pull request #64
Opened 2022-01-10 18:09 UTC by Drekorian

![seat-legend](https://user-images.githubusercontent.com/125338/148816808-850fbd24-4bd8-4cbc-b7e1-1727723baee3.png)

2022-01-11 06:57 UTC, gerak-cz approved these changes

2022-01-11 06:57 UTC, gerak-cz commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/SeatLegend.kt
> +    content: @Composable () -> Unit,
Can there really be anything other than plain text?

2022-01-11 15:58 UTC, hrach requested changes

2022-01-12 13:55 UTC, Drekorian commented on ui/src/main/java/kiwi/orbit/compose/ui/controls/SeatLegend.kt
> +                    fontWeight = FontWeight(450),
![450](https://user-images.githubusercontent.com/125338/149153467-2bd51652-4d6f-4234-9344-0604e69b9b9e.png)

I used Figma as the quote-unquote _source of truth_. Changed to `bodyNormal`.

2022-01-12 14:05 UTC, hrach approved these changes

2022-01-12 14:06 UTC, merged